import { Space, Table, Tag } from 'antd';
const columns = [
  {
    title: 'Mes',
    dataIndex: 'mes',
    key: 'mes',
  },
  {
    title: 'SKU',
    dataIndex: 'sku',
    key: 'sku',
  },
  {
    title: 'Market',
    dataIndex: 'market',
    key: 'market',
  },
  {
    title: 'Visualizaciones',
    dataIndex: 'visualizaciones',
    key: 'visualizaciones',
  },
  {
    title: 'Inversión',
    dataIndex: 'inversion',
    key: 'inversion',
  },
  {
    title: 'Clicks',
    dataIndex: 'clicks',
    key: 'clicks',
  },
  {
    title: 'CTR',
    dataIndex: 'ctr',
    key: 'ctr',
  },
  {
    title: 'CPC',
    dataIndex: 'cpc',
    key: 'cpc',
  },
  {
    title: 'Ordenes',
    dataIndex: 'ordenes',
    key: 'ordenes',
  },
  {
    title: 'Ventas',
    dataIndex: 'ventas',
    key: 'ventas',
  },
  {
    title: 'ACOS',
    dataIndex: 'acos',
    key: 'acos',
  }
];
const data = [
	{
		key: '1',
		sku: 'John Brown',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'New York No. 1 Lake Park',
		tags: ['nice', 'developer'],
	},
	{
		key: '2',
		sku: 'Jim Green',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 42,
		address: 'London No. 1 Lake Park',
		tags: ['loser'],
	},
	{
		key: '3',
		sku: 'Joe Black',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'Sidney No. 1 Lake Park',
		tags: ['cool', 'teacher'],
	},
	{
		key: '4',
		sku: 'John Brown',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'New York No. 1 Lake Park',
		tags: ['nice', 'developer'],
	},
	{
		key: '5',
		sku: 'Jim Green',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 42,
		address: 'London No. 1 Lake Park',
		tags: ['loser'],
	},
	{
		key: '6',
		sku: 'Joe Black',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'Sidney No. 1 Lake Park',
		tags: ['cool', 'teacher'],
	},
	{
		key: '7',
		sku: 'John Brown',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'New York No. 1 Lake Park',
		tags: ['nice', 'developer'],
	},
	{
		key: '8',
		sku: 'Jim Green',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 42,
		address: 'London No. 1 Lake Park',
		tags: ['loser'],
	},
	{
		key: '9',
		sku: 'Joe Black',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'Sidney No. 1 Lake Park',
		tags: ['cool', 'teacher'],
	},
	{
		key: '10',
		sku: 'John Brown',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'New York No. 1 Lake Park',
		tags: ['nice', 'developer'],
	},
	{
		key: '11',
		sku: 'Jim Green',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 42,
		address: 'London No. 1 Lake Park',
		tags: ['loser'],
	},
	{
		key: '12',
		sku: 'Joe Black',
		market: 'Amazon',
		visualizaciones: 'TOP',
		mes: 'mayo',
		inversion: 100,
		clicks: 30,
		ctr: 10,
		cpc: 100,
		ordenes: 'Varias',
		ventas: 80,
		acos: '-',
		age: 32,
		address: 'Sidney No. 1 Lake Park',
		tags: ['cool', 'teacher'],
	},
];

const Products = () => <Table columns={columns} dataSource={data} />;

export default Products;